#!/usr/bin/env python3
"""Regenerate the batched NNUE make loops in nnue_opt.asm.

These routines are fully unrolled 64-element bodies (one instruction line
per element), which is tedious and error-prone to maintain by hand. This script
generates them from the per-element templates below and splices them into
nnue_opt.asm between nn_apply_sub_ ENDP and the nn_fwd_eval_ section.

They write the CHILD slot of the ply-indexed accumulator (nn_acc[ply+1][j] =
nn_acc[ply][j] + delta[j], slots are contiguous 256-byte blocks), so undo is a
nn_ply decrement with no restore memcpy. nn_make_move holds both buffer bases
(4 address registers: to, from, src, dst); nn_make_cap needs the three w1 rows
plus dst, so it derives src as dst - 256 via a constant disp16.

Run:  python gen_nnue_batch.py [--check]
        --check: verify the current nnue_opt.asm matches what would be
                 generated (exit 0 = match, 1 = stale), no rewrite.

The generated code is deterministic: the same script + the same templates
always produce the same bytes, so the file can be diffed across edits.
"""

import os
import sys

ASM = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nnue_opt.asm")
N = 64  # hidden width; every element uses byte weight offset +d and acc offset +2d


def _move_body():
    """dst[j] = src[j] + w1[to][j] - w1[from][j]; si=to, bx=from, bp=src, di=dst."""
    lines = []
    for d in range(N):
        lines += [
            "        mov     al, [si+%d]" % d,   # w1[to_row][d]
            "        cbw",
            "        mov     dx, ax",
            "        mov     al, [bx+%d]" % d,   # w1[from_row][d]
            "        cbw",
            "        sub     dx, ax",            # to - from
            "        mov     ax, es:[bp+%d]" % (2 * d),  # src[j] (slot nn_ply)
            "        add     ax, dx",
            "        mov     es:[di+%d], ax" % (2 * d),  # dst[j] = src[j] + delta
        ]
    return "\n".join(lines)


def _cap_body():
    """dst[j] = src[j] + w1[to][j] - w1[from][j] - w1[cap][j].
    si=to, bx=from, bp=cap, di = dst base (slot nn_ply+1 + persp*128); the src
    (slot nn_ply) is di - 256, a constant disp16. dx is the delta temp."""
    lines = []
    for d in range(N):
        lines += [
            "        mov     al, [si+%d]" % d,   # w1[to_row][d]
            "        cbw",
            "        mov     dx, ax",
            "        mov     al, [bx+%d]" % d,   # w1[from_row][d]
            "        cbw",
            "        sub     dx, ax",
            "        mov     al, ds:[bp+%d]" % d,  # w1[cap_row][d] (BP, DS override)
            "        cbw",
            "        sub     dx, ax",            # to - from - cap
            "        mov     ax, es:[di-%d]" % (256 - 2 * d),  # src[j] = dst-256
            "        add     ax, dx",
            "        mov     es:[di+%d], ax" % (2 * d),         # dst[j]
        ]
    return "\n".join(lines)


def _shl(reg, times):
    return "\n".join("        shl     %s, 1" % reg for _ in range(times))


HEADER = (
    "; =====================================================================\n"
    "; nn_make_move_ - batched PLY-INDEXED NNUE make for a NORMAL move\n"
    "; (quiet or non-capture promo): nn_acc[ply+1][j] = nn_acc[ply][j] +\n"
    "; w1[to_row*64+j] - w1[from_row*64+j] in ONE pass, writing the CHILD slot\n"
    "; of the accumulator stack so undo is a nn_ply decrement (no 256-byte\n"
    "; restore memcpy). src = slot nn_ply (via the _nn_ply global), dst = the\n"
    "; slot 256 bytes after it. Calling convention: FAR, ax=persp, dx=to_row,\n"
    "; bx=from_row. Preserves bx,bp,si,di,ds; clobbers ax,dx,cx,es. Bit-identical\n"
    "; to the in-place RMW (i16 arithmetic mod 2^16).\n"
    "; GENERATED by gen_nnue_batch.py - edit the script, not this block.\n"
    "nn_make_move_ PROC FAR\n"
    "        push    bx\n"
    "        push    bp\n"
    "        push    si\n"
    "        push    di\n"
    "        push    ds\n"
    "        mov     si, dx\n"
    + _shl("si", 6)
    + "\n"
    + _shl("bx", 6)
    + "\n"
    "        mov     di, OFFSET _nn_acc\n"
    "        mov     cx, ss:_nn_ply\n"
    + _shl("cx", 8)
    + "\n"
    "        add     di, cx\n"
    "        mov     bp, di\n"
    "        add     di, 256\n"
    + _shl("ax", 7)
    + "\n"
    "        add     bp, ax\n"
    "        add     di, ax\n"
    "        mov     ax, SEG _nn_w1\n"
    "        mov     ds, ax\n"
    "        add     si, OFFSET _nn_w1\n"
    "        add     bx, OFFSET _nn_w1\n"
    "        mov     ax, ss\n"
    "        mov     es, ax\n"
)

MOVE_FOOTER = (
    "\n"
    "        pop     ds\n"
    "        pop     di\n"
    "        pop     si\n"
    "        pop     bp\n"
    "        pop     bx\n"
    "        retf\n"
    "nn_make_move_ ENDP\n"
)

CAP_HEADER = (
    "\n"
    "; nn_make_cap_ - batched PLY-INDEXED NNUE make for a CAPTURE or EP:\n"
    "; nn_acc[ply+1][j] = nn_acc[ply][j] + w1[to_row*64+j] - w1[from_row*64+j]\n"
    "; - w1[cap_row*64+j] in ONE pass into the CHILD slot. The three w1 rows use\n"
    "; si/bx/bp and dst uses di, so the src (slot nn_ply) is read as di - 256\n"
    "; (a constant disp16 - the child slot is always 256 bytes past its parent).\n"
    "; Calling convention: FAR, ax=persp, dx=to_row, bx=from_row, cx=cap_row.\n"
    "; Preserves bx,bp,si,di,ds; clobbers ax,dx,cx,es.\n"
    "; GENERATED by gen_nnue_batch.py - edit the script, not this block.\n"
    "nn_make_cap_ PROC FAR\n"
    "        push    bx\n"
    "        push    bp\n"
    "        push    si\n"
    "        push    di\n"
    "        push    ds\n"
    "        mov     si, dx\n"
    + _shl("si", 6)
    + "\n"
    + _shl("bx", 6)
    + "\n"
    "        mov     bp, cx\n"
    + _shl("bp", 6)
    + "\n"
    "        mov     di, OFFSET _nn_acc\n"
    "        mov     cx, ss:_nn_ply\n"
    + _shl("cx", 8)
    + "\n"
    "        add     di, cx\n"
    "        add     di, 256\n"
    + _shl("ax", 7)
    + "\n"
    "        add     di, ax\n"
    "        mov     ax, SEG _nn_w1\n"
    "        mov     ds, ax\n"
    "        add     si, OFFSET _nn_w1\n"
    "        add     bx, OFFSET _nn_w1\n"
    "        add     bp, OFFSET _nn_w1\n"
    "        mov     ax, ss\n"
    "        mov     es, ax\n"
)

CAP_FOOTER = (
    "\n"
    "        pop     ds\n"
    "        pop     di\n"
    "        pop     si\n"
    "        pop     bp\n"
    "        pop     bx\n"
    "        retf\n"
    "nn_make_cap_ ENDP\n"
)


def generate():
    return (HEADER + _move_body() + MOVE_FOOTER + CAP_HEADER
            + _cap_body() + CAP_FOOTER)


MARKER = "; nn_fwd_eval_ - NNUE forward pass via per-slot product tables."


def main():
    gen = generate()
    with open(ASM, "r") as f:
        content = f.read()

    # locate the splice points
    start = content.index("nn_apply_sub_ ENDP")
    start = content.index("\n", start) + 1          # after ENDP
    end = content.index(MARKER)
    # the marker line follows the generated section; keep the separator comment
    new_content = content[:start] + "\n" + gen + "\n; =====================================================================\n" + content[end:]

    if "--check" in sys.argv:
        if new_content == content:
            print("nnue_opt.asm is up to date.")
            return 0
        print("nnue_opt.asm is STALE - run gen_nnue_batch.py to regenerate.")
        return 1

    with open(ASM, "w") as f:
        f.write(new_content)
    print("Regenerated %s" % ASM)
    return 0


if __name__ == "__main__":
    sys.exit(main())
